export const Images ={
    cover: require ("@/assets/images/coverHome.png"),
    turkey:require ("@/assets/images/turkey.png"),
    egypt:require ("@/assets/images/egypt.jpg"),
    tunisia: require ("@/assets/images/tunisia.jpg"),
    argos:require ("@/assets/images/argos.jpg"),
    iberostart: require ("@/assets/images/iberostart.jpg"),
    beach: require ("@/assets/images/beach.jpg"),
    tennis: require ("@/assets/images/tennis.jpg"),
    exploreImage: require ("@/assets/images/explore.png"),
    profile: require ("@/assets/images/profile.jpg"),
    beachIcon: require("@/assets/images/beach.png"),
    golfIcon:require("@/assets/images/golf.png"),
    wellBeingIcon:require("@/assets/images/massage.png"),
    kitesurfingIcon:require("@/assets/images/kitesurf.png"),
    restaurantIcon:require("@/assets/images/assiette.png"),
    barIcon:require("@/assets/images/bar.png"),
    climatisuerIcon:require("@/assets/images/climatisuer.png"),
    poolIcon:require("@/assets/images/pool.png"),
    sportIcon:require("@/assets/images/sport.png"),
    wifiIcon:require("@/assets/images/wifi.png"),
    bookingHotel:require("@/assets/images/bookingHotel.jpg"),
    hotel:require("@/assets/images/hotel.jpg"),
    hotelPool:require("@/assets/images/hotelPool.jpg"),
    map:require("@/assets/images/map.png"),
    room:require("@/assets/images/room.png"),
    hotelResturant:require("@/assets/images/hotelResturant.jpg"),
    room2:require("@/assets/images/room2.jpg"),
    room3:require("@/assets/images/room3.png"),
    room4:require("@/assets/images/room4.jpg"),
    visa: require("@/assets/images/visa.png"),
    paypal:require("@/assets/images/paypal.png"),
    cardBack:require("@/assets/images/card-back.png"),
    cardFront:require("@/assets/images/card-front.png"),
    puce:require("@/assets/images/puce.png"),
    masterCard:require("@/assets/images/MasterCard.png"),
    americanExpress:require("@/assets/images/americanExpress.png"),
    reseauCard:require("@/assets/images/reseauCard.png"),
    valise:require("@/assets/images/valise.png"),
    login:require("@/assets/images/login.png"),
    start:require("@/assets/images/start.jpg"),
    samigo:require("@/assets/images/samigo.png"),
} 